insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Toddy Scarffe', '2 Messerschmidt Court', '1998-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Matt Faich', '49592 Oxford Place', '1999-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gillian Woodhams', '7330 Bunting Point', '2002-11-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Helen-elizabeth Moulding', '73913 Calypso Drive', '1999-03-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Abagail Clyma', '186 Golden Leaf Trail', '2005-03-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gardy Gurry', '45403 Cambridge Way', '1999-09-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kate Cholton', '25861 Katie Place', '2005-02-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Siouxie Crosio', '65 Pankratz Hill', '1996-07-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Enrica Patterson', '861 Lighthouse Bay Street', '2005-07-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cristen Dumbreck', '00158 Elgar Plaza', '1998-05-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Siobhan Willarton', '056 Randy Center', '1997-01-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bertrand Fendt', '25 Novick Hill', '2002-04-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ynes Denver', '65 Atwood Street', '2001-09-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donny Dudin', '16 Spohn Parkway', '1999-01-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corri Shorey', '14729 Orin Street', '2005-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gibbie Vears', '16 Hoepker Alley', '2000-05-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jacintha Raeburn', '97 Sloan Circle', '2004-05-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lidia Dockreay', '396 Jackson Center', '2000-05-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cairistiona Hurlestone', '86364 Eastlawn Junction', '1996-01-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carter Pask', '52654 Sunbrook Lane', '2004-12-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ruthy Adacot', '5 Crowley Hill', '2005-10-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Iolanthe Lerwell', '4117 Lyons Way', '2003-09-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Linn Huccaby', '775 Elka Hill', '2005-07-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andee Tredget', '294 Columbus Way', '1998-09-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liliane Coot', '8256 Kim Court', '2005-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Willey Caney', '055 Scott Point', '1998-03-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bria Lemonby', '77 Westridge Center', '2001-07-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Susi Dedney', '711 Rigney Trail', '2004-03-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rebe Steljes', '80571 Duke Point', '2002-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('York Antowski', '08509 Manley Park', '2002-07-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Robby Ridesdale', '9 Algoma Place', '1999-02-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Beckie Amiable', '30722 Arapahoe Junction', '2000-03-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Darwin Lewcock', '408 Forest Lane', '2001-09-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Conway Colleck', '99 Bartelt Center', '2002-08-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Audrie Jentet', '510 Clyde Gallagher Drive', '1996-06-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rickie Brandom', '02 Sugar Plaza', '1999-12-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carry Dally', '652 Eliot Terrace', '2003-04-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angele Worsall', '2 Eliot Trail', '2000-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeramey Khan', '3 Rockefeller Pass', '1997-05-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Evangeline Budnik', '8488 Haas Hill', '1997-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Helena Bachshell', '919 Tomscot Center', '1998-04-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Grissel Wonham', '3 Roxbury Place', '1996-10-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Yardley Moralas', '11 Calypso Lane', '2002-05-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jeanette Trippitt', '289 Everett Alley', '2004-02-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dalli Hadingham', '54264 Hauk Terrace', '2003-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Roselin Milward', '30942 Hagan Drive', '1999-02-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liv Hazeldean', '96596 Becker Point', '1996-05-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Graeme Speedy', '43 8th Plaza', '1999-03-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Christoffer Labeuil', '799 Hovde Drive', '1999-09-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Griffin Buckle', '7 Darwin Avenue', '2001-01-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thorpe Delf', '07284 1st Circle', '2005-10-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lolita Caslane', '32064 Birchwood Drive', '1999-05-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Antonin Elt', '386 Fair Oaks Way', '1997-11-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ilyse Gathercole', '539 Crescent Oaks Crossing', '2003-06-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lanette Klimko', '06 Ryan Way', '2004-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bartholemy Grzes', '103 Cody Lane', '1998-10-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Georgie Durston', '355 Tennessee Place', '1998-08-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Minor Marrow', '5 Lien Circle', '1999-09-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Myrwyn Hedgecock', '89 Russell Center', '1997-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maddy Bayns', '3 Reindahl Junction', '2002-05-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Guillermo Sweed', '628 Raven Trail', '2003-08-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Baily Maeer', '6372 Ruskin Point', '2001-08-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rhodie Mauger', '48 Delladonna Center', '2002-05-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Simon Salterne', '8610 Schmedeman Street', '2004-11-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aura Vanacci', '46 Atwood Place', '2005-08-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gladi Kahn', '74 Saint Paul Trail', '1996-09-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jozef Krolak', '60435 Swallow Alley', '1999-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Byram Bielfeld', '4 Maryland Circle', '1998-09-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Griswold Boxill', '6 Oak Park', '2002-11-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cam McClory', '50416 Alpine Street', '2000-04-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Thomasine Weatherhogg', '820 Briar Crest Lane', '1997-11-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Moll Jerdon', '45626 Burning Wood Road', '2005-07-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Willey Dabrowski', '5029 Green Ridge Alley', '2005-01-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Torrie Colthurst', '72 Prentice Parkway', '2004-09-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Filberte Barrack', '62590 Graedel Center', '2004-11-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Steward Kliche', '35 Warrior Circle', '1999-02-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Weber Tarte', '77 Hovde Center', '2003-03-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Consuela Kleinplatz', '20 Lerdahl Plaza', '2002-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kara-lynn Forshaw', '9 Lawn Avenue', '2002-07-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lorelei Porker', '2 Lotheville Park', '2005-05-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rogers Bloan', '3649 Mariners Cove Pass', '1996-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Issiah Rookeby', '43362 Texas Circle', '2002-03-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Goldie O'' Cloney', '29 International Terrace', '1997-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corbett Dungay', '3595 Bartelt Hill', '2001-12-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gayla Newtown', '8 Ryan Parkway', '2001-12-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Winthrop Brookz', '1356 Sugar Lane', '2000-10-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Delcine Habercham', '6 Pleasure Circle', '1998-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fin Knevett', '30365 Veith Place', '1996-03-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carson Suttling', '76 Park Meadow Alley', '2004-02-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tomasina Tavener', '7356 Buhler Plaza', '2000-01-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Neill O''Siaghail', '27585 Delaware Point', '2001-04-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nissie Aldington', '9 Stephen Hill', '1996-09-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hugo Goodhay', '0596 Hanover Crossing', '1997-02-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eugine Pirouet', '424 Kedzie Hill', '1999-07-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Zeke Symcox', '257 Village Hill', '1996-06-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clara Malyj', '59 Nelson Junction', '1997-11-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlane Brome', '075 Troy Point', '1996-08-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gwenore Ziehms', '76 Butterfield Crossing', '2004-04-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tammie Kington', '66665 Katie Center', '1997-10-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gabriela Ruecastle', '41877 Kinsman Center', '1998-07-12');
