insert into trayecto (id_tren, id_estacion, nombre) values (16, 89, 'Summer Ridge');
insert into trayecto (id_tren, id_estacion, nombre) values (76, 28, 'Paget');
insert into trayecto (id_tren, id_estacion, nombre) values (30, 20, 'Westerfield');
insert into trayecto (id_tren, id_estacion, nombre) values (17, 81, 'Colorado');
insert into trayecto (id_tren, id_estacion, nombre) values (2, 89, 'Hoffman');
insert into trayecto (id_tren, id_estacion, nombre) values (48, 4, 'Little Fleur');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 52, 'Colorado');
insert into trayecto (id_tren, id_estacion, nombre) values (55, 8, 'Forest Dale');
insert into trayecto (id_tren, id_estacion, nombre) values (84, 97, 'Scott');
insert into trayecto (id_tren, id_estacion, nombre) values (51, 96, 'Morning');
insert into trayecto (id_tren, id_estacion, nombre) values (45, 43, 'Melvin');
insert into trayecto (id_tren, id_estacion, nombre) values (8, 1, 'Petterle');
insert into trayecto (id_tren, id_estacion, nombre) values (57, 22, 'Bowman');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 48, 'Jenna');
insert into trayecto (id_tren, id_estacion, nombre) values (90, 26, 'Luster');
insert into trayecto (id_tren, id_estacion, nombre) values (1, 9, 'Dayton');
insert into trayecto (id_tren, id_estacion, nombre) values (6, 70, 'Claremont');
insert into trayecto (id_tren, id_estacion, nombre) values (36, 22, 'Nova');
insert into trayecto (id_tren, id_estacion, nombre) values (65, 100, 'Dwight');
insert into trayecto (id_tren, id_estacion, nombre) values (8, 16, 'Susan');
insert into trayecto (id_tren, id_estacion, nombre) values (56, 79, 'Gina');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 35, 'Commercial');
insert into trayecto (id_tren, id_estacion, nombre) values (72, 64, '1st');
insert into trayecto (id_tren, id_estacion, nombre) values (20, 81, 'Memorial');
insert into trayecto (id_tren, id_estacion, nombre) values (9, 78, 'Dwight');
insert into trayecto (id_tren, id_estacion, nombre) values (10, 39, 'Mayfield');
insert into trayecto (id_tren, id_estacion, nombre) values (61, 67, 'Elka');
insert into trayecto (id_tren, id_estacion, nombre) values (21, 50, 'Golden Leaf');
insert into trayecto (id_tren, id_estacion, nombre) values (65, 19, 'Menomonie');
insert into trayecto (id_tren, id_estacion, nombre) values (91, 75, 'School');
insert into trayecto (id_tren, id_estacion, nombre) values (83, 80, 'Ridgeway');
insert into trayecto (id_tren, id_estacion, nombre) values (10, 19, 'Comanche');
insert into trayecto (id_tren, id_estacion, nombre) values (65, 5, 'Thierer');
insert into trayecto (id_tren, id_estacion, nombre) values (7, 43, 'Spaight');
insert into trayecto (id_tren, id_estacion, nombre) values (30, 53, 'Loomis');
insert into trayecto (id_tren, id_estacion, nombre) values (43, 1, 'Barnett');
insert into trayecto (id_tren, id_estacion, nombre) values (70, 45, 'Colorado');
insert into trayecto (id_tren, id_estacion, nombre) values (80, 8, 'Pine View');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 7, 'Westerfield');
insert into trayecto (id_tren, id_estacion, nombre) values (93, 80, 'Commercial');
insert into trayecto (id_tren, id_estacion, nombre) values (1, 86, 'Spaight');
insert into trayecto (id_tren, id_estacion, nombre) values (23, 93, 'Utah');
insert into trayecto (id_tren, id_estacion, nombre) values (63, 15, 'Fieldstone');
insert into trayecto (id_tren, id_estacion, nombre) values (58, 86, 'Sachs');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 78, 'Johnson');
insert into trayecto (id_tren, id_estacion, nombre) values (83, 77, 'Scofield');
insert into trayecto (id_tren, id_estacion, nombre) values (48, 92, 'Lighthouse Bay');
insert into trayecto (id_tren, id_estacion, nombre) values (25, 35, 'Reinke');
insert into trayecto (id_tren, id_estacion, nombre) values (54, 9, 'Fieldstone');
insert into trayecto (id_tren, id_estacion, nombre) values (35, 35, 'Portage');
insert into trayecto (id_tren, id_estacion, nombre) values (49, 64, 'Elmside');
insert into trayecto (id_tren, id_estacion, nombre) values (92, 3, 'Arkansas');
insert into trayecto (id_tren, id_estacion, nombre) values (54, 41, 'Manitowish');
insert into trayecto (id_tren, id_estacion, nombre) values (38, 25, 'Corben');
insert into trayecto (id_tren, id_estacion, nombre) values (45, 34, 'Fuller');
insert into trayecto (id_tren, id_estacion, nombre) values (32, 36, 'Dahle');
insert into trayecto (id_tren, id_estacion, nombre) values (28, 91, 'Warbler');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 96, 'Lien');
insert into trayecto (id_tren, id_estacion, nombre) values (25, 21, 'Eliot');
insert into trayecto (id_tren, id_estacion, nombre) values (67, 50, 'Clemons');
insert into trayecto (id_tren, id_estacion, nombre) values (29, 41, 'Express');
insert into trayecto (id_tren, id_estacion, nombre) values (49, 76, 'Prairieview');
insert into trayecto (id_tren, id_estacion, nombre) values (47, 35, 'Arrowood');
insert into trayecto (id_tren, id_estacion, nombre) values (85, 64, 'Emmet');
insert into trayecto (id_tren, id_estacion, nombre) values (57, 82, 'Dayton');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 29, 'Old Shore');
insert into trayecto (id_tren, id_estacion, nombre) values (95, 24, 'Bartillon');
insert into trayecto (id_tren, id_estacion, nombre) values (90, 77, 'Spohn');
insert into trayecto (id_tren, id_estacion, nombre) values (78, 88, 'Rowland');
insert into trayecto (id_tren, id_estacion, nombre) values (32, 2, 'Namekagon');
insert into trayecto (id_tren, id_estacion, nombre) values (100, 9, 'Tennessee');
insert into trayecto (id_tren, id_estacion, nombre) values (86, 79, 'South');
insert into trayecto (id_tren, id_estacion, nombre) values (64, 1, 'Lindbergh');
insert into trayecto (id_tren, id_estacion, nombre) values (73, 11, 'Leroy');
insert into trayecto (id_tren, id_estacion, nombre) values (75, 49, 'Paget');
insert into trayecto (id_tren, id_estacion, nombre) values (83, 46, 'Colorado');
insert into trayecto (id_tren, id_estacion, nombre) values (37, 61, 'Brickson Park');
insert into trayecto (id_tren, id_estacion, nombre) values (6, 71, 'Coleman');
insert into trayecto (id_tren, id_estacion, nombre) values (80, 17, 'Veith');
insert into trayecto (id_tren, id_estacion, nombre) values (43, 62, '1st');
insert into trayecto (id_tren, id_estacion, nombre) values (92, 1, 'Meadow Valley');
insert into trayecto (id_tren, id_estacion, nombre) values (39, 83, 'Johnson');
insert into trayecto (id_tren, id_estacion, nombre) values (4, 62, 'Algoma');
insert into trayecto (id_tren, id_estacion, nombre) values (93, 37, 'Waywood');
insert into trayecto (id_tren, id_estacion, nombre) values (44, 6, 'Luster');
insert into trayecto (id_tren, id_estacion, nombre) values (40, 62, 'La Follette');
insert into trayecto (id_tren, id_estacion, nombre) values (18, 84, 'Southridge');
insert into trayecto (id_tren, id_estacion, nombre) values (60, 89, 'Mcguire');
insert into trayecto (id_tren, id_estacion, nombre) values (94, 59, 'Mccormick');
insert into trayecto (id_tren, id_estacion, nombre) values (8, 94, 'Merrick');
insert into trayecto (id_tren, id_estacion, nombre) values (50, 34, 'Carpenter');
insert into trayecto (id_tren, id_estacion, nombre) values (55, 77, 'Lakeland');
insert into trayecto (id_tren, id_estacion, nombre) values (99, 70, 'Hazelcrest');
insert into trayecto (id_tren, id_estacion, nombre) values (7, 52, 'Birchwood');
insert into trayecto (id_tren, id_estacion, nombre) values (25, 95, 'Holy Cross');
insert into trayecto (id_tren, id_estacion, nombre) values (19, 46, 'Kensington');
insert into trayecto (id_tren, id_estacion, nombre) values (13, 12, 'Westport');
insert into trayecto (id_tren, id_estacion, nombre) values (28, 41, 'Claremont');
insert into trayecto (id_tren, id_estacion, nombre) values (53, 58, 'Goodland');
insert into trayecto (id_tren, id_estacion, nombre) values (42, 51, 'Sachtjen');
