insert into tren (modelo, capacidad) values ('Ram 1500', 261);
insert into tren (modelo, capacidad) values ('Swift', 130);
insert into tren (modelo, capacidad) values ('xA', 253);
insert into tren (modelo, capacidad) values ('Wrangler', 118);
insert into tren (modelo, capacidad) values ('Silhouette', 299);
insert into tren (modelo, capacidad) values ('F250', 219);
insert into tren (modelo, capacidad) values ('4Runner', 83);
insert into tren (modelo, capacidad) values ('J', 33);
insert into tren (modelo, capacidad) values ('S6', 245);
insert into tren (modelo, capacidad) values ('Jetta', 29);
insert into tren (modelo, capacidad) values ('MX-5', 200);
insert into tren (modelo, capacidad) values ('XK Series', 128);
insert into tren (modelo, capacidad) values ('Silhouette', 98);
insert into tren (modelo, capacidad) values ('Cayenne', 120);
insert into tren (modelo, capacidad) values ('Savana 1500', 24);
insert into tren (modelo, capacidad) values ('V50', 250);
insert into tren (modelo, capacidad) values ('Corvette', 109);
insert into tren (modelo, capacidad) values ('Ram 3500', 83);
insert into tren (modelo, capacidad) values ('Ram Van B150', 59);
insert into tren (modelo, capacidad) values ('Corolla', 269);
insert into tren (modelo, capacidad) values ('Montero Sport', 177);
insert into tren (modelo, capacidad) values ('7 Series', 23);
insert into tren (modelo, capacidad) values ('E-Class', 264);
insert into tren (modelo, capacidad) values ('Grand Prix', 263);
insert into tren (modelo, capacidad) values ('Sportage', 132);
insert into tren (modelo, capacidad) values ('Quest', 190);
insert into tren (modelo, capacidad) values ('S-Series', 97);
insert into tren (modelo, capacidad) values ('Sentra', 86);
insert into tren (modelo, capacidad) values ('HHR', 216);
insert into tren (modelo, capacidad) values ('G37', 270);
insert into tren (modelo, capacidad) values ('Sonata', 114);
insert into tren (modelo, capacidad) values ('Escalade EXT', 196);
insert into tren (modelo, capacidad) values ('Avalanche 2500', 27);
insert into tren (modelo, capacidad) values ('Durango', 231);
insert into tren (modelo, capacidad) values ('RX-7', 108);
insert into tren (modelo, capacidad) values ('Taurus X', 207);
insert into tren (modelo, capacidad) values ('S-Class', 117);
insert into tren (modelo, capacidad) values ('DeVille', 45);
insert into tren (modelo, capacidad) values ('Impreza', 178);
insert into tren (modelo, capacidad) values ('Alcyone SVX', 282);
insert into tren (modelo, capacidad) values ('Escalade ESV', 245);
insert into tren (modelo, capacidad) values ('Bonneville', 261);
insert into tren (modelo, capacidad) values ('Liberty', 235);
insert into tren (modelo, capacidad) values ('Insight', 98);
insert into tren (modelo, capacidad) values ('E250', 150);
insert into tren (modelo, capacidad) values ('RX', 207);
insert into tren (modelo, capacidad) values ('Aerio', 47);
insert into tren (modelo, capacidad) values ('Camry', 103);
insert into tren (modelo, capacidad) values ('Spectra', 41);
insert into tren (modelo, capacidad) values ('Outback', 208);
insert into tren (modelo, capacidad) values ('Sky', 206);
insert into tren (modelo, capacidad) values ('Vanagon', 247);
insert into tren (modelo, capacidad) values ('T100', 241);
insert into tren (modelo, capacidad) values ('Silhouette', 156);
insert into tren (modelo, capacidad) values ('Astro', 241);
insert into tren (modelo, capacidad) values ('200', 259);
insert into tren (modelo, capacidad) values ('XLR-V', 210);
insert into tren (modelo, capacidad) values ('Tracer', 64);
insert into tren (modelo, capacidad) values ('Z4', 178);
insert into tren (modelo, capacidad) values ('Riviera', 184);
insert into tren (modelo, capacidad) values ('M', 172);
insert into tren (modelo, capacidad) values ('S60', 265);
insert into tren (modelo, capacidad) values ('S6', 255);
insert into tren (modelo, capacidad) values ('Sierra 3500', 230);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 195);
insert into tren (modelo, capacidad) values ('Esprit', 124);
insert into tren (modelo, capacidad) values ('A4', 31);
insert into tren (modelo, capacidad) values ('323', 112);
insert into tren (modelo, capacidad) values ('Express', 86);
insert into tren (modelo, capacidad) values ('430', 215);
insert into tren (modelo, capacidad) values ('M5', 280);
insert into tren (modelo, capacidad) values ('Tacoma', 209);
insert into tren (modelo, capacidad) values ('Ranger', 193);
insert into tren (modelo, capacidad) values ('CC', 36);
insert into tren (modelo, capacidad) values ('Justy', 145);
insert into tren (modelo, capacidad) values ('Samurai', 184);
insert into tren (modelo, capacidad) values ('Celica', 92);
insert into tren (modelo, capacidad) values ('S10 Blazer', 234);
insert into tren (modelo, capacidad) values ('Vision', 47);
insert into tren (modelo, capacidad) values ('Taurus', 170);
insert into tren (modelo, capacidad) values ('Regal', 108);
insert into tren (modelo, capacidad) values ('Sienna', 140);
insert into tren (modelo, capacidad) values ('A7', 200);
insert into tren (modelo, capacidad) values ('LTD', 258);
insert into tren (modelo, capacidad) values ('Venza', 136);
insert into tren (modelo, capacidad) values ('Fifth Ave', 222);
insert into tren (modelo, capacidad) values ('Vandura 3500', 278);
insert into tren (modelo, capacidad) values ('Galant', 232);
insert into tren (modelo, capacidad) values ('S-Class', 126);
insert into tren (modelo, capacidad) values ('Freestar', 189);
insert into tren (modelo, capacidad) values ('SLS-Class', 210);
insert into tren (modelo, capacidad) values ('Riviera', 270);
insert into tren (modelo, capacidad) values ('IS', 66);
insert into tren (modelo, capacidad) values ('Mustang', 224);
insert into tren (modelo, capacidad) values ('Caprice', 22);
insert into tren (modelo, capacidad) values ('Q', 273);
insert into tren (modelo, capacidad) values ('Bonneville', 173);
insert into tren (modelo, capacidad) values ('Optima', 100);
insert into tren (modelo, capacidad) values ('Tahoe', 198);
insert into tren (modelo, capacidad) values ('ZDX', 232);
