insert into tren (modelo, capacidad) values ('Rabbit', 1);
insert into tren (modelo, capacidad) values ('Crown Victoria', 2);
insert into tren (modelo, capacidad) values ('LeMans', 3);
insert into tren (modelo, capacidad) values ('Cabriolet', 4);
insert into tren (modelo, capacidad) values ('Bravada', 5);
insert into tren (modelo, capacidad) values ('S4', 6);
insert into tren (modelo, capacidad) values ('Ion', 7);
insert into tren (modelo, capacidad) values ('Dakota Club', 8);
insert into tren (modelo, capacidad) values ('H3', 9);
insert into tren (modelo, capacidad) values ('Paseo', 10);
insert into tren (modelo, capacidad) values ('Eos', 11);
insert into tren (modelo, capacidad) values ('Savana 2500', 12);
insert into tren (modelo, capacidad) values ('Colt Vista', 13);
insert into tren (modelo, capacidad) values ('Malibu', 14);
insert into tren (modelo, capacidad) values ('Sequoia', 15);
insert into tren (modelo, capacidad) values ('Express 2500', 16);
insert into tren (modelo, capacidad) values ('CL-Class', 17);
insert into tren (modelo, capacidad) values ('RX-7', 18);
insert into tren (modelo, capacidad) values ('LS', 19);
insert into tren (modelo, capacidad) values ('Caravan', 20);
insert into tren (modelo, capacidad) values ('Eclipse', 21);
insert into tren (modelo, capacidad) values ('Firefly', 22);
insert into tren (modelo, capacidad) values ('Suburban 2500', 23);
insert into tren (modelo, capacidad) values ('Savana 1500', 24);
insert into tren (modelo, capacidad) values ('Patriot', 25);
insert into tren (modelo, capacidad) values ('A8', 26);
insert into tren (modelo, capacidad) values ('Dakota Club', 27);
insert into tren (modelo, capacidad) values ('Safari', 28);
insert into tren (modelo, capacidad) values ('Focus', 29);
insert into tren (modelo, capacidad) values ('M3', 30);
insert into tren (modelo, capacidad) values ('Villager', 31);
insert into tren (modelo, capacidad) values ('A6', 32);
insert into tren (modelo, capacidad) values ('F250', 33);
insert into tren (modelo, capacidad) values ('Dakota Club', 34);
insert into tren (modelo, capacidad) values ('Town & Country', 35);
insert into tren (modelo, capacidad) values ('CR-V', 36);
insert into tren (modelo, capacidad) values ('Catera', 37);
insert into tren (modelo, capacidad) values ('Riviera', 38);
insert into tren (modelo, capacidad) values ('X5 M', 39);
insert into tren (modelo, capacidad) values ('Outback Sport', 40);
insert into tren (modelo, capacidad) values ('Villager', 41);
insert into tren (modelo, capacidad) values ('F250', 42);
insert into tren (modelo, capacidad) values ('323', 43);
insert into tren (modelo, capacidad) values ('Swift', 44);
insert into tren (modelo, capacidad) values ('E-Series', 45);
insert into tren (modelo, capacidad) values ('XC70', 46);
insert into tren (modelo, capacidad) values ('Maxima', 47);
insert into tren (modelo, capacidad) values ('Sonoma Club', 48);
insert into tren (modelo, capacidad) values ('MKX', 49);
insert into tren (modelo, capacidad) values ('A8', 50);
insert into tren (modelo, capacidad) values ('3500', 51);
insert into tren (modelo, capacidad) values ('Caravan', 52);
insert into tren (modelo, capacidad) values ('Silverado 1500', 53);
insert into tren (modelo, capacidad) values ('SL-Class', 54);
insert into tren (modelo, capacidad) values ('FX', 55);
insert into tren (modelo, capacidad) values ('GX', 56);
insert into tren (modelo, capacidad) values ('XK Series', 57);
insert into tren (modelo, capacidad) values ('Rainier', 58);
insert into tren (modelo, capacidad) values ('Vision', 59);
insert into tren (modelo, capacidad) values ('Talon', 60);
insert into tren (modelo, capacidad) values ('Grand Prix', 61);
insert into tren (modelo, capacidad) values ('Sportage', 62);
insert into tren (modelo, capacidad) values ('Cultus', 63);
insert into tren (modelo, capacidad) values ('Turbo Firefly', 64);
insert into tren (modelo, capacidad) values ('Mark VIII', 65);
insert into tren (modelo, capacidad) values ('Grand Vitara', 66);
insert into tren (modelo, capacidad) values ('tC', 67);
insert into tren (modelo, capacidad) values ('XL-7', 68);
insert into tren (modelo, capacidad) values ('Challenger', 69);
insert into tren (modelo, capacidad) values ('Leone', 70);
insert into tren (modelo, capacidad) values ('Silverado', 71);
insert into tren (modelo, capacidad) values ('Veyron', 72);
insert into tren (modelo, capacidad) values ('TL', 73);
insert into tren (modelo, capacidad) values ('Savana 1500', 74);
insert into tren (modelo, capacidad) values ('Grand Am', 75);
insert into tren (modelo, capacidad) values ('Fox', 76);
insert into tren (modelo, capacidad) values ('E-Series', 77);
insert into tren (modelo, capacidad) values ('Mustang', 78);
insert into tren (modelo, capacidad) values ('Silverado 3500', 79);
insert into tren (modelo, capacidad) values ('968', 80);
insert into tren (modelo, capacidad) values ('Jetta', 81);
insert into tren (modelo, capacidad) values ('S-Type', 82);
insert into tren (modelo, capacidad) values ('ES', 83);
insert into tren (modelo, capacidad) values ('H1', 84);
insert into tren (modelo, capacidad) values ('GX', 85);
insert into tren (modelo, capacidad) values ('Corvette', 86);
insert into tren (modelo, capacidad) values ('Avalon', 87);
insert into tren (modelo, capacidad) values ('Spider', 88);
insert into tren (modelo, capacidad) values ('TSX', 89);
insert into tren (modelo, capacidad) values ('Jetta', 90);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 91);
insert into tren (modelo, capacidad) values ('Grand Am', 92);
insert into tren (modelo, capacidad) values ('Thunderbird', 93);
insert into tren (modelo, capacidad) values ('F-Series', 94);
insert into tren (modelo, capacidad) values ('Lumina', 95);
insert into tren (modelo, capacidad) values ('Seville', 96);
insert into tren (modelo, capacidad) values ('Skylark', 97);
insert into tren (modelo, capacidad) values ('Thunderbird', 98);
insert into tren (modelo, capacidad) values ('M3', 99);
insert into tren (modelo, capacidad) values ('Aerostar', 100);
